modLoader = "javafml"
loaderVersion = "[43,)"
issueTrackerURL = "https://github.com/satyrnidae/early-game-buckets/issues"
license = "MIT"

[[mods]]
modId = "early_buckets"
version = "${version}"
displayName = "Early Game Buckets"
authors = "Isabel Maskrey"
description = '''
Adds new buckets made from materials other than iron!
'''
logoFile = "icon.png"

[[dependencies.early_buckets]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.early_buckets]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.early_buckets]]
modId = "architectury"
mandatory = true
versionRange = "[6.6.92,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.early_buckets]]
modId = "jei"
mandatory = false
versionRange = "[11.8.1,)"
ordering = "AFTER"
side = "BOTH"
