@MethodsReturnNonnullByDefault @FieldsAreNonnullByDefault @VariablesAreNonnullByDefault @ParametersAreNonnullByDefault
package dev.satyrn.early_buckets.mixin.advancements;

import dev.satyrn.early_buckets.annotations.VariablesAreNonnullByDefault;
import net.minecraft.FieldsAreNonnullByDefault;
import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;