@MethodsReturnNonnullByDefault @FieldsAreNonnullByDefault
package dev.satyrn.early_buckets.fabriclike;

import net.minecraft.FieldsAreNonnullByDefault;
import net.minecraft.MethodsReturnNonnullByDefault;