@MethodsReturnNonnullByDefault @FieldsAreNonnullByDefault
package dev.satyrn.early_buckets.advancements.criterion;

import net.minecraft.FieldsAreNonnullByDefault;
import net.minecraft.MethodsReturnNonnullByDefault;