@MethodsReturnNonnullByDefault @FieldsAreNonnullByDefault
package dev.satyrn.early_buckets.fabriclike.client;

import net.minecraft.FieldsAreNonnullByDefault;
import net.minecraft.MethodsReturnNonnullByDefault;